# Generated by Django 2.2.6 on 2019-10-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='users',
        ),
    ]
