# Generated by Django 2.2.6 on 2019-10-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'In progess'), (100, 'Finished')], default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_country', models.CharField(max_length=3)),
                ('receive_country', models.CharField(max_length=3)),
                ('send_currency', models.CharField(max_length=3)),
                ('receive_currency', models.CharField(max_length=3)),
                ('send_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('receive_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('send_fees', models.DecimalField(decimal_places=4, max_digits=20)),
                ('exrate_service', models.DecimalField(decimal_places=4, max_digits=20)),
                ('exrate_market', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('funds_in', models.CharField(max_length=100)),
                ('funds_out', models.CharField(max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'Error')], default=1)),
                ('error_details', models.CharField(blank=True, max_length=500, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.ScrapeJob')),
                ('scraper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.Scraper')),
            ],
            options={
                'db_table': 'transfer_items',
            },
        ),
    ]
