# Generated by Django 2.2.6 on 2019-10-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_scrapejob_scraper_transferitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(max_length=3)),
                ('currency_to', models.CharField(max_length=3)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange_rates',
            },
        ),
    ]
