# Generated by Django 2.2.6 on 2019-10-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitem',
            name='exrate_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.ExchangeRate'),
        ),
    ]
