# Generated by Django 2.2.6 on 2019-10-03 15:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_auto_20191003_1431'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='scraper',
            managers=[
                ('active_scrapers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
