# Generated by Django 2.2.6 on 2019-10-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_auto_20191003_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In progress'), (100, 'Successfully finished'), (101, 'Finished with error')], default=1),
        ),
    ]
