# Generated by Django 2.2.6 on 2019-10-03 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_auto_20191003_1542'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='scraper',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exrates', to='transfers.ScrapeJob'),
        ),
    ]
