# Generated by Django 2.2.6 on 2019-10-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0008_auto_20191003_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitem',
            name='actual_trans',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='exrate_market_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='fee_conversion',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='fx_cut',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='no_loss_trans',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='spread',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='take_rate',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='total_premium',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
