# Generated by Django 2.2.6 on 2019-10-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0010_auto_20191005_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitem',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='speed',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
