# Generated by Django 2.2.6 on 2019-10-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0011_auto_20191008_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitem',
            name='speed',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
