# Generated by Django 2.2.6 on 2019-10-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0012_auto_20191010_0842'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scrapejob',
            table='jobs',
        ),
        migrations.AlterModelTable(
            name='scraper',
            table='companies',
        ),
    ]
