# Generated by Django 2.2.6 on 2019-10-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0013_auto_20191016_0750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repo',
        ),
    ]
