# Generated by Django 2.2.6 on 2019-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0015_transferamount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferamount',
            options={'ordering': ('value',)},
        ),
        migrations.AddField(
            model_name='scraper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
