# Generated by Django 2.2.6 on 2019-10-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0016_auto_20191017_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitem',
            name='funds_out',
            field=models.CharField(max_length=250),
        ),
    ]
