# Generated by Django 2.2.7 on 2019-11-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0017_auto_20191026_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferitem',
            options={'ordering': ['scraper_id', 'send_country', 'receive_country', 'send_amount']},
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
