# Generated by Django 2.2.7 on 2019-11-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0018_auto_20191119_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitem',
            name='total_pay',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
